Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
license_his = (
    df_active["license"]
    .value_counts()
    .to_frame()
    .rename_axis("license_names")
    .reset_index()
)
fig = px.pie(license_his, values="license", names="license_names", color_discrete_sequence=color_discrete_sequence, hole=0.2)

fig.update_layout(showlegend=False, font_size=16)
fig.update_traces(textposition='inside', textinfo='percent+label', marker=dict(line=dict(color=boarder_color, width=1)))

fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 11[0m
[1;32m      8[0m fig [38;5;241m=[39m px[38;5;241m.[39mpie(license_his, values[38;5;241m=[39m[38;5;124m"[39m[38;5;124mlicense[39m[38;5;124m"[39m, names[38;5;241m=[39m[38;5;124m"[39m[38;5;124mlicense_names[39m[38;5;124m"[39m, color_discrete_sequence[38;5;241m=[39mcolor_discrete_sequence, hole[38;5;241m=[39m[38;5;241m0.2[39m)
[1;32m     10[0m fig[38;5;241m.[39mupdate_layout(showlegend[38;5;241m=[39m[38;5;28;01mFalse[39;00m, font_size[38;5;241m=[39m[38;5;241m16[39m)
[0;32m---> 11[0m fig[38;5;241m.[39mupdate_traces(textposition[38;5;241m=[39m[38;5;124m'[39m[38;5;124minside[39m[38;5;124m'[39m, textinfo[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpercent+label[39m[38;5;124m'[39m, marker[38;5;241m=[39m[38;5;28mdict[39m(line[38;5;241m=[39m[38;5;28mdict[39m(color[38;5;241m=[39m[43mboarder_color[49m, width[38;5;241m=[39m[38;5;241m1[39m)))
[1;32m     13[0m fig[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'boarder_color' is not defined
NameError: name 'boarder_color' is not defined

